server:
  Address: 127.0.0.1:8081
  ServerAgent: gtoken-demo
  LogPath: ./example/logs

gToken:
  # 缓存模式 1 gcache 2 gredis
  CacheMode: 1
  # 是否支持多端登录
  MultiLogin: true

# Redis 配置
redis:
  default:
    address: 10.96.81.240:6379
    db: 0
    pass:
